name: Update CV

on:
  # Permite ejecutarlo manualmente desde la pesta√±a Actions
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate CV
        uses: CandyGZ/cv-fromGit-SAAS@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          api_url: "https://cv-from-git-saas.vercel.app" # O la URL que te proporcionen
          api_key: ${{ secrets.CV_API_KEY }} # Tu clave comprada

      - name: Commit and Push CV
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add cv.md
          git commit -m "Update CV [skip ci]" || echo "No changes to commit"
          git push
